dist: trusty
before_install:
  - npm install -g npm@latest
  - npm set progress=false
install:
  - npm install
language: node_js
node_js:
  - "6.9"
  - "4.7"
script: npm run test:ci
after_success:
  - curl -Lo travis_after_all.py https://raw.githubusercontent.com/contentful/travis_after_all/master/travis_after_all.py
  - python travis_after_all.py
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
  - ./bin/coverage-test.sh 
addons:
  sauce_connect: true
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
